spring.application.name=labair-api

# to connect to the database
#spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_system?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# to automatically create the tables
spring.jpa.hibernate.ddl.auto=update

# to always run SQL scripts
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true